# File local riêng của máy bạn. File này đã được .gitignore.
# Điền giá trị thật vào đây để chạy PowerShell:
# $env:SPRING_PROFILES_ACTIVE="local"
# mvn clean spring-boot:run

# Redis Cache
spring.cache.type=redis
spring.redis.host=localhost
spring.redis.port=6379

# File Upload
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Database
spring.datasource.url=jdbc:postgresql://dpg-d936sh4m0tmc73d2l800-a.singapore-postgres.render.com:5432/careermate_db?sslmode=require
spring.datasource.username=careermate_user
spring.datasource.password=0vyi4U6doqYeuFeDRcu3jil8hr1R0xC7
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Mã bí mật để ký JWT
jwt.secret=26ee5428aaf636fc2c48b269aca43a8913d7b1e4dd08eb4c6ae6b943c4e826f708a9a488feb75fb34e80928bfa0b058ff06282c5829d4fb5777e55a2281f2e80
# Thời gian hết hạn của token
jwt.access-token-expiration=1800000
jwt.refresh-token-expiration=36000000

# --- Cấu hình Google OAuth2 ---
# Client ID 
google.client-id=YOUR_CLIENT_ID_HERE

# Client Secret 
google.client-secret=YOUR_CLIENT_SECRET_HERE

# Chỉ hiện cảnh báo (WARN) và lỗi (ERROR), ẩn INFO và DEBUG
logging.level.root=WARN

# Tắt banner Spring
spring.main.banner-mode=off

# Cloudinary
cloudinary.cloud-name=dpym64zg9
cloudinary.api-key=779575122511922
cloudinary.api-secret=hM75PBJdRUIWVZ9vsGfDChlFtPs

# Cấu hình API Key cho Google Gemini
gemini.api.keys=AIzaSyB0XynpcRk2mIHvH3LeX4Vpx2t5wg5fS1E,AIzaSyAbF8hm-wSwyM9mUWoRdIQqc5puQQ1Rauo,AIzaSyAlHVe8JwGrbAp9QrmpbXQLJDbmU_XaO6c,AIzaSyAcX9rPO2hftpI8G-LoulyWUFMbNnFbOAw,AIzaSyCcek-O7UGX9A9aKpposIQIGYfzxqvLrWo

# ===== Email Configuration (Gmail SMTP) =====
# Bắt buộc để gửi mail Quên mật khẩu / Xác thực
spring.mail.host=smtp.gmail.com
spring.mail.port=587
# Email gửi đi
spring.mail.username=n.dd.huy.05@gmail.com
# Mật khẩu ứng dụng (App Password)
spring.mail.password=afucppsngijnpfcj
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
# Hiển thị log
# 1. Hide Hibernate SQL statement logs (the "Hibernate: select ...")
# We use logging level instead of spring.jpa.show-sql for more control
logging.level.org.hibernate.SQL=WARN
# 2. Hide other informational Hibernate messages
logging.level.org.hibernate.orm=WARN

# 3. Explicitly disable the open-in-view warning
spring.jpa.open-in-view=false
cors.allowed-origins=*